#!/bin/bash
# =============================================================================
# Description:
#   Extracts the 'origin' remote URL from the current Git repository,
#   transforms the SSH-style URL into a browsable HTTP URL, and launches
#   it in the default web browser.
#
# Usage:
#   git open
# =============================================================================

strindex() {
  x="${1%%$2*}"
  if [[ $x = $1 ]]; then
    return -1
  else
    return ${#x}
  fi
}

remote_url=$(git remote -v | grep origin | tail -n 1 | cut -d$'\t' -f2 | cut -d' ' -f1)

# Get first occurance of '@' and tail the remote_url at that position
strindex "$remote_url" "@"
index=$?+1
url_tail=${remote_url:index}

# Replace any colons with forward slashes and convert into an web URL
browsable_url="https://$(echo "$url_tail" | sed 's/:/\//g')"

# Launch URL
if [ $(uname) = "Darwin" ]; then
  open $browsable_url
else
  xdg-open $browsable_url
fi
