#!/bin/bash

# Opens the current git repo in your browser

strindex() {
  x="${1%%$2*}"
  if [[ $x = $1 ]]; then
    return -1
  else
    return ${#x}
  fi
}

remote_url=$(git remote get-url origin)

# Get first occurance of '@' and tail the remote_url at that position
strindex "$remote_url" "@"
index=$?+1
url_tail=${remote_url:index}

# Replace any colons with forward slashes
browsable_url=$(echo "$url_tail" | sed 's/:/\//g')

# Launch URL
if [ $(uname) = "Darwin" ]; then
  open "http://$browsable_url"
# TODO: Handle linux systems with an else here
fi
